server: irc.freenode.net
port: 6667
channel: '#non_existent_channel'
nickname: example_irc_bot
nickpass: null
timezone: local
disabled_commands: []
admins: []
prompt: '!'
blacklist: []
other:
  user-agent: null
  some-api-key: null