server: irc.freenode.net
port: 6667
channel: '#non_existent_channel'
nickname: example_irc_bot
nickpass: null
timezone: local
disabled_commands: []
enabled_plugins: null
admins: []
prompt: '!'
blacklist: []
other:
  user-agent: null
  google-api-key: null
  google-search-engine: null
  nsjail_path: null
